In [1]:
import numpy as np

In these exercises, where possible, try to utilize the available numpy functionality rather than native python code.

# Exercise 1. 



Consider the $3\times 5$ array a3by5 created below.

In [2]:
a3by5 = np.random.random((3,5))
a3by5

array([[0.15709767, 0.02751046, 0.95941507, 0.51932666, 0.34591179],
       [0.59388649, 0.43782484, 0.3089075 , 0.17557081, 0.1485992 ],
       [0.84625706, 0.7329847 , 0.33740307, 0.79575042, 0.93520238]])

Flatten it and sort the list.


# Exercise 2.


Consider the arrays x, y and z below.

In [4]:
x = np.array([-4, -3, -2, -1, 1, 2, 3, 4])
y = np.array([-3, -2, -1, 0, 1, 2, 3])
z = np.array([0, 0, 0, 0])

I. Write some code to test whether 

1. at least one of the elements in the array is non-zero.
2. all of the elements in the array are non-zero.
3. at least one of the elements in the array is equal to zero.  

and apply it to each of the three arrays.

II. Add 5 to every positive entry in each array.

# Exercise 3

Consider the Pauli matrices defined below.

1. Verify that they are traceless
2. Verify that they have determinants -1.
3. Verify that they are Hermitian.
4. Verify that they are unitary.
5. Verify the SU(2) algebra, i.e., the commutation relations among the Pauli matrices. If you don't remember the formulas, derive them.


In [32]:
sigX = np.matrix([[0+0j,1+0j],[1+0j,0+0j]])
sigY = np.matrix([[0+0j,0-1j],[0+1j,0+0j]])
sigZ = np.matrix([[1+0j,0+0j],[0+0j,-1+0j]])
print(sigX) 
print(sigY)
print(sigZ)

[[0.+0.j 1.+0.j]
 [1.+0.j 0.+0.j]]
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]
[[ 1.+0.j  0.+0.j]
 [ 0.+0.j -1.+0.j]]


# End of the exercises

## Solutions

### Exercise 1

In [12]:
a3by5 = np.random.random((3,5))
print(a3by5)

print(np.sort(a3by5, axis=None))

[[0.46191155 0.31315343 0.49754762 0.73900679 0.38005595]
 [0.8228595  0.00234374 0.58786674 0.11546514 0.88952217]
 [0.66410259 0.31486303 0.85561344 0.81522911 0.60800278]]
[0.00234374 0.11546514 0.31315343 0.31486303 0.38005595 0.46191155
 0.49754762 0.58786674 0.60800278 0.66410259 0.73900679 0.81522911
 0.8228595  0.85561344 0.88952217]


### Exercise 2

In [10]:
x = np.array([-4, -3, -2, -1, 1, 2, 3, 4])
y = np.array([-3, -2, -1, 0, 1, 2, 3])
z = np.array([0, 0, 0, 0])

print('at least one non-zero element in x = ', np.any(x))
print('at least one non-zero element in y = ', np.any(y))
print('at least one non-zero element in z = ', np.any(z))
print('zero is absent in x = ', np.all(x))
print('zero is absent in y = ', np.all(y))
print('zero is absent in z = ', np.all(z))
print('at least one zero element in x = ', np.any(x==0))
print('at least one zero element in y = ', np.any(y==0))
print('at least one zero element in z = ', np.any(z==0))

at least one non-zero element in x =  True
at least one non-zero element in y =  True
at least one non-zero element in z =  False
zero is absent in x =  True
zero is absent in y =  False
zero is absent in z =  False
at least one zero element in x =  False
at least one zero element in y =  True
at least one zero element in z =  True


### Exercise 3

In [48]:
print('Traces:       ', np.trace(sigX), np.trace(sigY), np.trace(sigZ))
print('Determinants: ', np.linalg.det(sigX), np.linalg.det(sigY), np.linalg.det(sigZ))
print('sigmaX is Hermitian = ', np.all(sigX-sigX.H==0))
print('sigmaY is Hermitian = ', np.all(sigY-sigY.H==0))
print('sigmaZ is Hermitian = ', np.all(sigZ-sigZ.H==0))
print('[X,Y]=2iZ           = ', np.all(np.dot(sigX,sigY)-np.dot(sigY,sigX)-2j*sigZ==0))
print('[Y,Z]=2iX           = ', np.all(np.dot(sigY,sigZ)-np.dot(sigZ,sigY)-2j*sigX==0))
print('[Z,X]=2iY           = ', np.all(np.dot(sigZ,sigX)-np.dot(sigX,sigZ)-2j*sigY==0))

Traces:        0j 0j 0j
Determinants:  (-1+0j) (-1+0j) (-1+0j)
sigmaX is Hermitian =  True
sigmaY is Hermitian =  True
sigmaZ is Hermitian =  True
[X,Y]=2iZ           =  True
[Y,Z]=2iX           =  True
[Z,X]=2iY           =  True
